function bestPath(targetSum, array) {
    const table = Array(targetSum + 1);
    table.fill(null);

    table[0] = []; // Initialize the table because 0 can be generated by an empty array

    for (let i = 0; i <= targetSum; i++){
        if (table[i] !== null){
            for (let num of array) {
                let newCombination = [...table[i], num];
                if (!table[i + num] || table[i + num].length > newCombination.length) {
                    table[i + num] = [...newCombination];
                }
            }
        }
    }
    return table[targetSum];
}




console.log(bestPath(8, [2, 3, 5]))// [5,3]
console.log(bestPath(100, [1,2,,5,25])) // [25,25,25,25]